### ISSUE TITLE
Cannot animate marker from one location to another

### ISSUE THREAD

**Issue by sundeepkvkl** [IndoorLocation/polestar-indoor-location-provider-android#1]
The current API allows to create and remove markers. But I couldn't fins a way to animate a marker from one location to another.

**Comment by mathieugerard** [comment]
Hi,
Are you looking to move a Marker on the Mapwize Map?
Have a look at the Mapwize Android SDK doc. There is a setLatLngFloor. https://docs.mapwize.io/developers/android/sdk/latest/javadoc/index.html
However I don't see the link with the Pole Star Location Provider.
Mathieu
